### PR TITLE
Change package TAG for SBo repo to "custom".

### PR DESCRIPTION
**Pull request by Ponce**
See http://slackbuilds.org/faq/#package_repos

### CODE REVIEW

**Comment by Ponce** [comment]
this is to avoid people building packages by default with a _SBo TAG.

it's a proposal: if ok I'll do another pull request for the file 40-sbo.repo.

**Comment by willysr** [comment]
40-sbo.repo is using the default repository for SBo
Do you mean 60-SBo-current.repo ?

**Comment by Ponce** [comment]
no, I mean 40-sbo.repo.

the proposal is to avoid using sbopkg to build packages with a TAG "_SBo" by default.

60-SBo-current.repo already has set a "ponce" TAG variable and that should be fine according to the proposal (but could be set to another too, it's ok for me).

**Comment by willysr** [comment]
That is applicable for those who wanted to redistribute the packages again.
What if they want to use it personally ? Do they also have to use "custom" TAG?

**Comment by rworkman** [comment]
Hrm, maybe TAG should be _sbopkg instead by default - that way there's some intuitive insight into where the package came from...

**Comment by Ponce** [comment]
willysr: no, it's a precaution just for redistribution.
this is because I've seen packages tagged _SBo being ditributed in random places and I thought this way we can avoid it: I don't think it's done by purpose, it's just that it's the default...

rworkman: yes, I think too it's better.

**Comment by willysr** [comment]
can you check this commit #da02b37 ?

**Comment by rworkman** [comment]
Looks good to me

**Comment by Ponce** [comment]
to me too

**Comment by willysr** [comment]
Applied to master

Thanks

**Pull request closed without merging**
