### PR TITLE
sqg: Parallelize building of all packages by option -j.

### PR DESCRIPTION
**Pull request by swmarc**
I found that creating queues for all packages takes ages so I implemented
a -j option to specify how many queue file generation processes should run in
parallel.

Parallelization requires GNU parallel to be installed else it falls back to the
old implementation.

### CODE REVIEW

**Comment by willysr** [comment]
I tested this PR and here's the results on my desktop with a dual core CPU

--> with the patch and parallel installed
time sqg -a -j 2
Processing all SlackBuilds in the SBo/14.2 repository...Done.

real    47m42.053s
user    27m13.030s
sys     15m39.714s

-- with the patch and parallel not installed
time sqg -a -j 2
Processing all SlackBuilds in the SBo/14.2 repository...Done.

real    44m6.025s
user    26m59.901s
sys     15m26.189s

**Comment by swmarc** [comment]
On 01/02/2017 10:09 AM, Willy Sudiarto Raharjo wrote:
> I tested this PR and here's the results on my desktop with a dual core CPU
> 
> --> with the patch and parallel installed
> time sqg -a -j 2
> Processing all SlackBuilds in the SBo/14.2 repository...Done.

It seems there's something wrong with parallel, because the output
should differ from yours.
On this test, there wasn't any active parallelization.
The check for parallel normally returned exit code 255, but it now
returns 0 (parallel --help &> /dev/null).
This is the reason with it's not working anymore.

> -- with the patch and parallel not installed
> time sqg -a -j 2
> Processing all SlackBuilds in the SBo/14.2 repository...Done.

The -j option has no effect if parallel is not installed.

Seems I'd need to fix it before you're able to see the speedup,
because it's a lot faster also on just 2 cores.

-marc

--------------------------------------------------------------------------------
PGP 32 bit Key ID: 0x69EC498D
PGP 64 bit Key ID: 0x8EE93B2D69EC498D
PGP Key fingerprint: D320 76CB 4053 D544 52BD  D461 8EE9 3B2D 69EC 498D

**Comment by willysr** [comment]
OK, i will wait for the update.

Thanks

**Comment by swmarc** [comment]
Thanks for letting me know. It's fixed now.

**Comment by willysr** [comment]
Now cut into half

time sqg -a -j 2
Processing all SlackBuilds in the SBo/14.2 repository...
Computers / CPU cores / Max jobs to run
1:local / 2 / 2

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.23s  local:0/6223/100%/0.2s      
Done.

real    23m30.894s
user    27m23.730s
sys     15m20.134s

**Comment by swmarc** [comment]
Great. This is the expected outcome.

**Comment by willysr** [comment]
but that's only the real time, not user/sys' time.

**Comment by swmarc** [comment]
Of course, because both threads together, to process the queue files, will need (roundabout) the same amount of (CPU-) time as one thread, but the real time is lower.

**Comment by willysr** [comment]
ok, cool. I will merge this branch after reviewing the texts. The functionality is OK for me

**Comment by willysr** [comment]
Squashed into a single commit on a separate branch, ready for merging to master when you are OK
1eb39ee

**Comment by swmarc** [comment]
Absolutely. Thanks.

**Pull request closed without merging**
