### PR TITLE
Viewing Queue shows repo version after Updates has been run.

### PR DESCRIPTION
**Pull request by Geremia**
implements #61 "Viewing Queue should have an upgrade version column."

### CODE REVIEW

**Comment by willysr** [comment]
So far it's good
i just need to do some cosmetic update regarding the dialog box height/width to accomodate this changes and we should be good.

also i noticed that this new change only works if you run Updates first and flag the queue from that menu. If you save the queue and load it in different session of sbopkg, the new UI will not show up.

**Comment by willysr** [comment]
merged

**Comment by Geremia** [comment]
@willysr 
>also i noticed that this new change only works if you run Updates first and flag the queue from that menu. If you save the queue and load it in different session of sbopkg, the new UI will not show up.
Yeah, ideally it would work for all queue items, but running `check_for_updates` every time before displaying the queue would be too slow. `check_for_updates` and `remove_obsolete_sources` desperately need parallelization somehow.

**Comment by willysr** [comment]
unfortunately there are a lot of things to be done in those two functions and they can't be paralelized.

**Comment by Geremia** [comment]
@willysr I tried [this quick fix](https://unix.stackexchange.com/a/103921/37153), but it didn't work…

**Pull request closed without merging**
