### PR TITLE
Moved sqg functions to /usr/libexec.

### PR DESCRIPTION
**Pull request by swmarc**

### CODE REVIEW

**Comment by willysr** [comment]
@swmarc : any strong reason to move this to another place?

**Comment by willysr** [comment]
is it due to FHS?
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html

**Comment by swmarc** [comment]
Yes, but also to be in line with existing Slackware tools like slackpkg, slacktrack, compat32pkg, multilibpkg, just to name a few. The update SlackBuild would follow after approval.

**Comment by willysr** [comment]
OK, +1 for me

I would prefer to push it in one merge, so please go ahead with the updated SlackBuild

**Comment by swmarc** [comment]
Thanks Willy.

**Pull request merged**
